### ISSUE TITLE
VS 2022: "System.IO.FileNotFoundException: Could not load file or assembly 'VSConsole, Culture=neutral'"

### ISSUE THREAD

**Issue by ElektroStudios** [mrlacey/VSConsole#21]
I'm having this exception on VS 2022 v17.5.4. The exception message is shown in the VSConsole floating window.

I'm on a WinForms VB.NET project targeting .NET Framework 4.8.

Steps to reproduce:
 1.  In a project just select: "View" -> "Other Windows" -> "VSConsole"
 
```
An exception was encountered while constructing the content of this frame.  This information is also logged in "C:\Users\Administrador\AppData\Roaming\Microsoft\VisualStudio\17.0_9453ed09\ActivityLog.xml".

Exception details:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'VSConsole, Culture=neutral' or one of its dependencies. El sistema no puede encontrar el archivo especificado.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at System.Windows.Navigation.BaseUriHelper.GetLoadedAssembly(String assemblyName, String assemblyVersion, String assemblyKey)
   at MS.Internal.AppModel.ResourceContainer.GetResourceManagerWrapper(Uri uri, String& partName, Boolean& isContentFile)
   at MS.Internal.AppModel.ResourceContainer.GetPartCore(Uri uri)
   at System.IO.Packaging.Package.GetPartHelper(Uri partUri)
   at System.IO.Packaging.Package.GetPart(Uri partUri)
   at System.Windows.Application.GetResourceOrContentPart(Uri uri)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at VSConsole.VSCToolWindowControl..ctor() in C:\code\GitHub\mrlacey\VSConsole\VSConsole\VSCToolWindowControl.xaml.cs:line 30
   at VSConsole.VSCToolWindow..ctor() in C:\code\GitHub\mrlacey\VSConsole\VSConsole\VSCToolWindow.cs:line 31
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.VisualStudio.Shell.Package.InstantiateToolWindow(Type toolWindowType, Object context)
   at Microsoft.VisualStudio.Shell.Package.<>c__DisplayClass84_0.<CreateToolWindow>g__CreateToolWindowWorker|1()
   at Microsoft.VisualStudio.Shell.Package.CreateToolWindow(Type toolWindowType, Int32 id, UInt32 flags, Object context, Guid persistenceGuid)
   at Microsoft.VisualStudio.Shell.Package.CreateToolWindow(Type toolWindowType, Int32 id, Object context)
   at Microsoft.VisualStudio.Shell.AsyncPackage.<CompleteToolWindowCreationAsync>d__39.MoveNext()
```

**Comment by mrlacey** [comment]
Thanks for reporting - I hadn't noticed this. Fixed in v 1.2
